### ISSUE TITLE
Playinfo decoding issue

### ISSUE THREAD

**Issue by gthieleb** [DominikWrobel/airmusic#4]
This message appears multiple times in the HA log.

```
Logger: homeassistant.helpers.entity
Quelle: helpers/entity.py:944
Erstmals aufgetreten: 07:56:41 (40 Vorkommnisse)
Zuletzt protokolliert: 08:36:40

Update for media_player.airmusic_radio fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 944, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/airmusic/media_player.py", line 239, in async_update
    await self._update_volume_info()
  File "/config/custom_components/airmusic/media_player.py", line 243, in _update_volume_info
    volume_xml = await self.request_call('/playinfo')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/airmusic/media_player.py", line 218, in request_call
    text = await resp.text()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1261, in text
    return self._body.decode(encoding, errors=errors)  # type: ignore[union-attr]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 210: invalid start byte
```

**Comment by DominikWrobel** [comment]
Could you copy me the all the info you are getting when typing your radios IP and /playinfo while playing an internet radio station? You can also try to set the language in the for the internal communication by using this command

http://[IP]/init?language=en

this will not change the language for the radio menu, but should help with this error.

**Comment by gthieleb** [comment]
A quick try with the url in the browser i get a 401. Will check later.

**Comment by DominikWrobel** [comment]
Your radio has auth enabled, the easiest way will be to use NodeRED and httprequest node with these credentials
user: su3g4go6sk7
pass: ji39454xu/^
